version: "3.7"

networks:
  cookbook-network:
  
services:
  cookbook-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "SqlServer_Docker2023"
        ACCEPT_EULA: "Y"
    networks:
      - cookbook-network
