name: Release to NuGet

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        
      - name: Start dependencies (docker-compose)
        run: |
          docker-compose up -d
          
      - name: Wait for SQL Server container
        run: sleep 30s
        shell: bash
        
      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack NuGets
        run: dotnet pack -c Release --no-build --output . /p:Version=${TAG_NAME}

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
