name: Release to NuGet

on:
  release:
    types: [ published ]
  
defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Pack NuGets
        run: dotnet pack -c Release --no-build --output . /p:Version=${TAG_NAME}
        
      - uses: actions/upload-artifact@v3
        with:
          name: Publish to artifacts
          if-no-files-found: error
          retention-days: 7
          path: /*.nupkg

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1

      - name: Build
        run: dotnet build -c Release

      
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [ create_nuget ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: .

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1

      - name: Publish NuGet package
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json --skip-duplicate
